### ISSUE TITLE
About training diffusion model

### ISSUE THREAD

**Issue by WhiteLie98** [tsachiblau/Threat-Model-Agnostic-Adversarial-Defense-using-Diffusion-Models#1]
Hi, I found that there is no sign of the training code for the Diffusion model. And I was wondering if the Diffusion model needs to be trained with adversarial examples.

**Comment by tsachiblau** [comment]
We used a vanilla trained diffusion model, supplied by https://github.com/ermongroup/ddim

**Comment by WhiteLie98** [comment]
Ok, thanks! Have you ever tried to train the Diffusion model with adversarial examples?

**Comment by tsachiblau** [comment]
Yes, it did not help to boost the performance.

**Comment by WhiteLie98** [comment]
Thanks a lot!
